### ISSUE TITLE
Public functions need doc comments (from the proto docs)

### ISSUE THREAD

**Issue by QuestofIranon** [hashgraph/hedera-sdk-go#17]
- [x] account_balance_query.go
 - [x] account_create_transaction.go
 - [x] account_delete_transaction.go
 - [x] account_id.go
 - [x] account_info_query.go
 - [x] account_records_query.go
 - [x] account_stakers_query.go
 - [x] account_update_transaction.go
 - [x] client.go
 - [x] consensus_message_submit_transaction.go
 - [x] consensus_message.go
 - [x] consensus_topic_create_transaction.go
 - [x] consensus_topic_delete_transaction.go
 - [x] consensus_topic_id.go
 - [x] consensus_topic_info_query.go
 - [x] consensus_topic_update_transaction.go
 - [x] contract_bytecode_query.go
 - [x] contract_call_query.go
 - [x] contract_create_transaction.go
 - [x] contract_delete_transaction.go
 - [x] contract_execute_transaction.go
 - [ ] contract_function_params.go
 - [x] contract_function_result.go
 - [ ] contract_function_selector.go
 - [x] contract_id.go
 - [x] contract_info_query.go
 - [x] contract_log_info.go
 - [x] contract_records_query.go
 - [x] contract_update_transaction.go
 - [x] crypto.go
 - [x] crypto_transfer_transaction.go
 - [x] entity_id.go
 - [x] errors.go
 - [x] file_append_transaction.go
 - [x] file_contents_query.go
 - [x] file_create_transaction.go
 - [x] file_delete_transaction.go
 - [x] file_id.go
 - [ ] file_info_query.go
 - [ ] file_update_transaction.go
 - [ ] freeze_transaction.go
 - [ ] get_by_solidity_id_query.go
 - [ ] hbar.go
 - [ ] hbar_unit.go
 - [ ] id.go
 - [ ] index.go
 - [ ] key_list.go
 - [ ] keystore.go
 - [ ] mirror_client.go
 - [ ] mirror_consensus_topic_query.go
 - [ ] mirror_subscription_handle.go
 - [ ] mnemonic.go
 - [ ] query_builder.go
 - [ ] status.go
 - [ ] system_delete_transaction.go
 - [ ] system_undelete_transaction.go
 - [ ] threshold_key.go
 - [ ] time.go
 - [ ] transaction.go
 - [ ] transfer.gotransaction_builder.go
 - [ ] transaction_id.go
 - [ ] transaction_receipt.go
 - [ ] transaction_receipt_query.go
 - [ ] transaction_record.go
 - [ ] transaction_record_query.go
 - [ ] transfer.go

 - [x] #17

**Comment by donaldthibeau** [comment]
In progress
