### ISSUE TITLE
E2E Tests for transactions and queries

### ISSUE THREAD

**Issue by QuestofIranon** [hashgraph/hedera-sdk-go#40]
- [x] account_balance_query.go #48
- [x] account_create_transaction.go #48 
- [x] account_delete_transaction.go #48 
- [x] account_info_query.go #48 
- [x] account_records_query.go
- [x] account_stakers_query.go
- [x] account_update_transaction.go #48 
- [x] consensus_message_submit_transaction.go #65 
- [x] consensus_topic_create_transaction.go #65 
- [x] consensus_topic_delete_transaction.go #65 
- [x] consensus_topic_info_query.go #65
- [x] consensus_topic_update_transaction.go #65 
- [x] contract_create_transaction.go  #63
- [x] contract_delete_transaction.go  #63
- [x] contract_execute_transaction.go   #63
- [x] contract_records_query.go
- [x] contract_update_query.go
- [x] contract_info_query.go  #63
- [x] crypto_transfer_transaction.go #48 
- [x] file_append_transaction.go #52
- [x] file_contents_query.go #52
- [x] file_create_transaction.go #52
- [x] file_delete_transaction.go #52 
- [x] file_info_query.go #52 
- [x] file_update_transaction.go #52
- [x] freeze_transaction.go
- [x] get_by_solidity_id_query.go
- [x] mirror_consensus_topic_query.go
- [x] system_delete_transaction.go
- [x] system_undelete_transaction.go
- [x] transaction_receipt_query.go
- [x] transaction_record_query.go

**Comment by mehcode** [comment]
@QuestofIranon Can you update the checklist?
