### ISSUE TITLE
Executable Structure Refactoring

### ISSUE THREAD

**Issue by NicolaMirchev** [hashgraph/hedera-sdk-go#832]
### Problem

Currently, the Go SDK suffers from multiple bad design decisions. There is a significant amount of duplicated code in the Transaction and Query structures. The code does not strictly adhere to the Go style guide. Additionally, some of the core functionality, particularly in executable.go, is difficult to test and requires further refactoring

### Solution

- Create root struct and interface - executable & Executable, which would hold all common fields, functions about queries & transactions. 
- - Example: 
```
type Executable interface {
GetMaxBackoff() time.Duration 
	GetMinBackoff() time.Duration
	GetGrpcDeadline() *time.Duration
	GetMaxRetry() int
	GetNodeAccountIDs() []AccountID
	GetLogLevel() *LogLevel


	shouldRetry(interface{}, interface{}) _ExecutionState
	makeRequest(interface{}) interface{}
	advanceRequest(interface{})
	getNodeAccountID(interface{}) AccountID
	getMethod(*_Channel) _Method
	mapStatusError(interface{}, interface{}) error
	mapResponse(interface{}, interface{}, AccountID, interface{}) (interface{}, error)
	getName() string
	validateNetworkOnIDs(client *Client) error
}
```
```
type executable struct {
	e              Executable
	transactionIDs *_LockableSlice
	nodeAccountIDs *_LockableSlice
	maxBackoff     *time.Duration
	minBackoff     *time.Duration
	grpcDeadline   *time.Duration
	maxRetry       int
	logLevel       *LogLevel
}
```
- Create sub-instances for `Query` & `Transaction`, which define common behaviours for the corresponding objects (structs)
- To accomplish it, extend executable interface and struct and safe reference to Executable inside the struct, so we can have a root `_Execute` function
- - Example for new transaction struct & interface:
```
type Transaction interface {
	Executable

	Execute(client *Client) (TransactionResponse, error)
	Sign(privateKey PrivateKey) Transaction
	SignWithOperator(client *Client) (Transaction, error)
	SignWith(publicKey PublicKey, signer TransactionSigner) Transaction
	AddSignature(publicKey PublicKey, signature []byte) Transaction
	Freeze() (Transaction, error)
	FreezeWith(client *Client) (Transaction, error)

	build() *services.TransactionBody
	buildScheduled() (*services.SchedulableTransactionBody, error)
}
```
type transaction struct {
	executable
	maxRetry int

	transactionFee           uint64
	defaultMaxTransactionFee uint64
	memo                     string
	transactionValidDuration *time.Duration
	transactionID            TransactionID

	transactions       *_LockableSlice
	signedTransactions *_LockableSlice

	publicKeys         []PublicKey
	transactionSigners []TransactionSigner

	freezeError error

	regenerateTransactionID bool
}
```
type transaction struct {
	executable
	maxRetry int

	transactionFee           uint64
	defaultMaxTransactionFee uint64
	memo                     string
	transactionValidDuration *time.Duration
	transactionID            TransactionID

	transactions       *_LockableSlice
	signedTransactions *_LockableSlice

	publicKeys         []PublicKey
	transactionSigners []TransactionSigner

	freezeError error

	regenerateTransactionID bool
}
```

```[tasklist]
### Tasks
- [ ] https://github.com/hashgraph/hedera-sdk-go/issues/834
- [ ] https://github.com/hashgraph/hedera-sdk-go/issues/835
- [ ] https://github.com/hashgraph/hedera-sdk-go/issues/833
```
